hack

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,15 +5,17 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: install-packages
-      run: sudo apt-get --yes update
-      run: DEBIAN_FRONTEND=noninteractive sudo apt-get --yes install gcc libreadline-dev flex bison make perl libipc-run-perl clang llvm-dev libperl-dev libpython-dev tcl-dev libldap2-dev libicu-dev docbook-xml docbook-xsl fop libxml2-utils xsltproc krb5-admin-server krb5-kdc krb5-user slapd ldap-utils libssl-dev pkg-config locales-all
+      run: sudo apt-get --yes update && apt-get --yes install gcc libreadline-dev flex bison make perl libipc-run-perl clang llvm-dev libperl-dev libpython-dev tcl-dev libldap2-dev libicu-dev docbook-xml docbook-xsl fop libxml2-utils xsltproc krb5-admin-server krb5-kdc krb5-user slapd ldap-utils libssl-dev pkg-config locales-all
+      env:
+      - DEBIAN_FRONTEND=noninteractive
     - name: configure
       run: ./configure --enable-cassert --enable-debug --enable-tap-tests --with-tcl --with-python --with-perl --with-ldap --with-openssl --with-icu --with-llvm
     - name: build
-      run: echo "COPT=-Wall -Werror" > src/Makefile.custom
-      run: make -s -j3
+      run: echo "COPT=-Wall -Werror" > src/Makefile.custom && make -s -j3
     - name: test
-      run: PG_TEST_EXTRA="ssl ldap kerberos" make -s check-world' || su postgres -c '( for F in ` find . -name initdb.log -o -name regression.diffs ` ; do echo === $F === ; head -1000 $F ; done ; exit 1 )'
+      run: make -s check-world' || ( for F in ` find . -name initdb.log -o -name regression.diffs ` ; do echo === $F === ; head -1000 $F ; done ; exit 1 )
+      env:
+      - PG_TEST_EXTRA="ssl ldap kerberos"
 
 #  test-macos:
 #    runs-on: macos-latest
